### ISSUE TITLE
Ember composable helpers 0.20+ broken

### ISSUE THREAD

**Issue by staale** [DockYard/ember-composable-helpers#144]
In v0.20 the code change to use es2016 modules I believe (at least from investigating the logs). This has broken intersect for us. We get:

    intersect.js:19 Uncaught TypeError: (0 , _emberMetalUtils.guidFor) is not a function

It seems that the guidFor method from the ember-metal/utils import is not working as intended. It seems that the object passed in from the define method for the ember-metal/utils is not the same that is returned from that file in ember.

Either I am doing something wrong in how I include ember (I am just adding a bower dependency), or there is something else not working as intended. Please advice, I would like to keep the library up to date.

**Comment by poteto** [comment]
What version of `ember-cli-shims` do you have installed?

**Comment by staale** [comment]
0.1.0

**Comment by poteto** [comment]
Please upgrade it to `0.1.1`, it includes a bugfix for `guidFor`.

**Comment by staale** [comment]
Ok, that worked. Thanks.

**Comment by lolmaus** [comment]
We're seeing 

    TypeError: (0 , _emberMetalUtils.guidFor) is not a function

in `ember-composable-helpers/helpers/append` `idForArray`.

Version `0.23.1`.

**Comment by martndemus** [comment]
You need to upgrade ember-cli-shims!

**Comment by lolmaus** [comment]
We can't, we're still on Ember 1.x. :(

**Comment by martndemus** [comment]
@lolmaus which exact version? It works with 1.13

**Comment by lolmaus** [comment]
@martndemus `ember-cli-shims` readme says that versions 0.1.0+ work only with Ember Data 2.3.0+.
